backend/src/main/java/com/celuveat/celuveat/common/config/JpaConfig.java, backend/src/main/java/com/celuveat/celuveat/common/domain/BaseEntity.java, backend/src/main/java/com/celuveat/celuveat/common/exception/BaseException.java, backend/src/main/java/com/celuveat/celuveat/common/exception/BaseExceptionType.java, backend/src/main/java/com/celuveat/celuveat/common/exception/ExceptionControllerAdvice.java, backend/src/main/java/com/celuveat/celuveat/common/exception/ExceptionResponse.java, backend/src/test/java/com/celuveat/celuveat/common/DataCleaner.java, backend/src/test/java/com/celuveat/celuveat/common/DataClearExtension.java
=> feat: 공통으로 사용할 예외와 엔티티를 정의

backend/src/main/java/com/celuveat/celuveat/celeb/Celeb.java, backend/src/main/java/com/celuveat/celuveat/celeb/CelebException.java, backend/src/main/java/com/celuveat/celuveat/celeb/CelebExceptionType.java, backend/src/main/java/com/celuveat/celuveat/restaurant/Category.java, backend/src/main/java/com/celuveat/celuveat/restaurant/Restaurant.java, backend/src/main/java/com/celuveat/celuveat/restaurant/RestaurantException.java, backend/src/main/java/com/celuveat/celuveat/restaurant/RestaurantExceptionType.java, backend/src/main/java/com/celuveat/celuveat/video/Video.java, backend/src/main/java/com/celuveat/celuveat/video/VideoException.java, backend/src/main/java/com/celuveat/celuveat/video/VideoExceptionType.java
=> feat: 셀럽 음식점 영상 도메인 생성

frontend/.storybook/preview.ts, frontend/package.json, frontend/src/styles/GlobalStyle.tsx, frontend/src/styles/GlobalStyles.tsx, frontend/src/styles/base.tsx, frontend/src/styles/reset.tsx, frontend/yarn.lock
=> chore: 스토리북 글로벌 스타일 적용

.github/CODEOWNERS
=> infra: CODEOWNERS 추가

backend/src/main/java/com/celuveat/celuveat/CeluveatApplication.java, backend/src/main/java/com/celuveat/celuveat/celeb/application/CelebQueryService.java, backend/src/main/java/com/celuveat/celuveat/celeb/application/dto/FindAllCelebResponse.java, backend/src/main/java/com/celuveat/celuveat/celeb/domain/Celeb.java, backend/src/main/java/com/celuveat/celuveat/celeb/exception/CelebException.java, backend/src/main/java/com/celuveat/celuveat/celeb/exception/CelebExceptionType.java, backend/src/main/java/com/celuveat/celuveat/celeb/infra/persistence/CelebDao.java, backend/src/main/java/com/celuveat/celuveat/celeb/infra/persistence/CelebQueryDao.java, backend/src/main/java/com/celuveat/celuveat/celeb/presentation/CelebController.java, backend/src/main/java/com/celuveat/celuveat/restaurant/Category.java, backend/src/main/java/com/celuveat/celuveat/restaurant/domain/Category.java, backend/src/main/java/com/celuveat/celuveat/restaurant/domain/Restaurant.java, backend/src/main/java/com/celuveat/celuveat/restaurant/exception/RestaurantException.java, backend/src/main/java/com/celuveat/celuveat/restaurant/exception/RestaurantExceptionType.java, backend/src/main/java/com/celuveat/celuveat/restaurant/infra/persistence/RestaurantDao.java, backend/src/main/java/com/celuveat/celuveat/video/domain/Video.java, backend/src/main/java/com/celuveat/celuveat/video/exception/VideoException.java, backend/src/main/java/com/celuveat/celuveat/video/exception/VideoExceptionType.java, backend/src/main/java/com/celuveat/celuveat/video/infra/persistence/VideoDao.java, backend/src/test/java/com/celuveat/celuveat/CeluveatApplicationTests.java, backend/src/test/java/com/celuveat/celuveat/acceptance/celeb/CelebAcceptanceTest.java, backend/src/test/java/com/celuveat/celuveat/celeb/application/CelebQueryServiceTest.java, backend/src/test/java/com/celuveat/celuveat/celeb/fixture/CelebFixture.java, backend/src/test/java/com/celuveat/celuveat/celeb/infra/persistence/CelebDaoTest.java, backend/src/test/java/com/celuveat/celuveat/celeb/infra/persistence/CelebQueryDaoTest.java, backend/src/test/java/com/celuveat/celuveat/celeb/infra/persistence/FakeCelebDao.java, backend/src/test/java/com/celuveat/celuveat/restaurant/fixture/RestaurantFixture.java, backend/src/test/java/com/celuveat/celuveat/restaurant/infra/persistence/RestaurantDaoTest.java, backend/src/test/java/com/celuveat/celuveat/video/fixture/VideoFixture.java, backend/src/test/java/com/celuveat/celuveat/video/infra/persistence/VideoDaoTest.java
=> feat: 셀럽 전체 조회 API 구현

backend/src/main/java/com/celuveat/celuveat/celeb/application/dto/FindAllCelebResponse.java, backend/src/main/java/com/celuveat/celuveat/celeb/domain/Celeb.java, backend/src/main/java/com/celuveat/celuveat/celeb/infra/persistence/CelebQueryDao.java, backend/src/main/java/com/celuveat/celuveat/restaurant/domain/Restaurant.java, backend/src/main/java/com/celuveat/celuveat/video/application/dto/FindAllVideoByRestaurantIdResponse.java, backend/src/main/java/com/celuveat/celuveat/video/domain/Video.java, backend/src/main/java/com/celuveat/celuveat/video/domain/VideoHistory.java, backend/src/main/java/com/celuveat/celuveat/video/exception/VideoHistoryException.java, backend/src/main/java/com/celuveat/celuveat/video/exception/VideoHistoryExceptionType.java, backend/src/main/java/com/celuveat/celuveat/video/infra/persistence/VideoHistoryDao.java, backend/src/main/java/com/celuveat/celuveat/video/infra/persistence/VideoQueryDao.java, backend/src/test/java/com/celuveat/celuveat/acceptance/video/VideoAcceptanceTest.java, backend/src/test/java/com/celuveat/celuveat/celeb/fixture/CelebFixture.java, backend/src/test/java/com/celuveat/celuveat/celeb/infra/persistence/CelebQueryDaoTest.java, backend/src/test/java/com/celuveat/celuveat/restaurant/fixture/RestaurantFixture.java, backend/src/test/java/com/celuveat/celuveat/video/fixture/VideoFixture.java, backend/src/test/java/com/celuveat/celuveat/video/fixture/VideoHistoryFixture.java, backend/src/test/java/com/celuveat/celuveat/video/infra/persistence/VideoHistoryDaoTest.java, backend/src/test/resources/schema.sql
=> feat: 변경된 DB & API 설계를 적용

frontend/src/components/@common/Button/TextButton.tsx, frontend/src/styles/GlobalStyles.ts, frontend/src/styles/base.ts, frontend/src/styles/reset.ts
=> fix: globalStyles에 존재하는 문제 개선 및 네이밍 수정

backend/src/main/java/com/celuveat/celuveat/restaurant/application/RestaurantQueryService.java, backend/src/main/java/com/celuveat/celuveat/restaurant/domain/Restaurant.java, backend/src/main/java/com/celuveat/celuveat/restaurant/presentation/RestaurantController.java, backend/src/test/java/com/celuveat/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/java/com/celuveat/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java, backend/src/test/java/com/celuveat/celuveat/restaurant/application/RestaurantQueryServiceTest.java
=> feat: 특정 음식점 조회 api 구현

backend/src/main/java/com/celuveat/celuveat/common/config/WebConfig.java, backend/src/main/java/com/celuveat/celuveat/common/page/Page.java, backend/src/main/java/com/celuveat/celuveat/common/page/PageCond.java, backend/src/main/java/com/celuveat/celuveat/common/page/PageCondArgumentResolver.java, backend/src/main/java/com/celuveat/celuveat/common/page/PageResponse.java, backend/src/main/java/com/celuveat/celuveat/common/page/SliceResponse.java, backend/src/main/java/com/celuveat/celuveat/restaurant/application/RestaurantQueryService.java, backend/src/main/java/com/celuveat/celuveat/restaurant/application/dto/RestaurantSearchResponse.java, backend/src/main/java/com/celuveat/celuveat/restaurant/infra/persistence/RestaurantQueryDao.java, backend/src/main/java/com/celuveat/celuveat/restaurant/presentation/RestaurantController.java, backend/src/main/java/com/celuveat/celuveat/video/domain/Video.java, backend/src/main/java/com/celuveat/celuveat/video/domain/VideoHistory.java, backend/src/test/java/com/celuveat/celuveat/acceptance/common/CommonAcceptanceSteps.java, backend/src/test/java/com/celuveat/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/java/com/celuveat/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java, backend/src/test/java/com/celuveat/celuveat/common/page/PageCondArgumentResolverTest.java, backend/src/test/java/com/celuveat/celuveat/common/page/PageCondTest.java, backend/src/test/java/com/celuveat/celuveat/restaurant/application/RestaurantQueryServiceTest.java, backend/src/test/java/com/celuveat/celuveat/restaurant/fixture/RestaurantFixture.java, backend/src/test/java/com/celuveat/celuveat/restaurant/infra/persistence/FakeRestaurantQueryDao.java, backend/src/test/java/com/celuveat/celuveat/restaurant/infra/persistence/RestaurantQueryDaoTest.java, backend/src/test/java/com/celuveat/celuveat/video/fixture/VideoFixture.java, backend/src/test/java/com/celuveat/celuveat/video/infra/persistence/FakeVideoDao.java, backend/src/test/resources/schema.sql
기능 구현하면서, 페이지 반환할 때 공통적으로 사용할 클래스들이랑 ArgumentResolver 정의해뒀어
close #14
=> feat: 셀럽으로 음식점 조회 api 구현

backend/src/main/java/com/celuveat/celuveat/admin/presentation/AdminController.java, backend/src/main/java/com/celuveat/celuveat/admin/presentation/dto/AdminLoginRequest.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml, backend/src/main/resources/sql/data.sql, backend/src/main/resources/sql/schema.sql, backend/src/test/resources/application.yml
```
- dev,test 환경에서 데이터베이스 스키마 SQL 작성
- dev,test 환경에서만 테이블을 생성 & 샘플 어드민을 등록하도록 스크립트를 작성
- 어드민 로그인 API 의 name 파라미터를 username으로 변경
```
<br><br>
- close #96 
<br><br>
=> feat: dev 환경에서 사용할 테이블 어드민 등록 스크립트 작성

backend/src/main/java/com/celuveat/celuveat/common/config/WebConfig.java, backend/src/main/resources/application.yml, backend/src/test/resources/application.yml
```
CORS 설정 추가
환경변수로 ALLOW_ORIGINS=origin1, origin2 와 같은 형식으로 사용할 수 있음
```
<br><br>
- close #97 
<br><br>
=> feat: cors 설정

frontend/src/components/@common/SearchBar/SearchBarDropDown.stories.tsx, frontend/src/components/@common/SearchBar/SearchBarDropDown.tsx, frontend/src/components/@common/SearchBar/SearchBarInput.tsx, frontend/src/components/@common/SearchBar/SearchBarSelectBox.tsx, frontend/src/components/@common/SearchBar/hooks/useSearchBarRef.tsx, frontend/src/components/@common/SearchBar/index.tsx
#106 
git 글로벌 설정으로 대소문자를 구분하게 설정을 추가하여 해결
```
git config core.ignorecase false
```
- close #106
=> Fix: 파일명 변경이 적용되지 않아 발생한 에러 해결

.github/CODEOWNERS
```
PR 요청시 리뷰어 자동 등록 설정 추가
```
<br><br>
- close #29 
<br><br>
=> infra: CODEOWNERS 등록

backend/src/main/java/com/celuveat/celeb/domain/Celeb.java, backend/src/main/java/com/celuveat/celeb/domain/CelebRepository.java, backend/src/main/java/com/celuveat/common/config/JpaConfig.java, backend/src/main/java/com/celuveat/common/domain/BaseEntity.java, backend/src/main/java/com/celuveat/common/exception/BaseException.java, backend/src/main/java/com/celuveat/common/exception/BaseExceptionType.java, backend/src/main/java/com/celuveat/common/exception/ExceptionControllerAdvice.java, backend/src/main/java/com/celuveat/common/exception/ExceptionResponse.java, backend/src/main/java/com/celuveat/restaurant/domain/Restaurant.java, backend/src/main/java/com/celuveat/restaurant/domain/RestaurantImage.java, backend/src/main/java/com/celuveat/restaurant/domain/RestaurantImageRepository.java, backend/src/main/java/com/celuveat/restaurant/domain/RestaurantRepository.java, backend/src/main/java/com/celuveat/restaurant/domain/SocialMedia.java, backend/src/main/java/com/celuveat/video/domain/Video.java, backend/src/main/java/com/celuveat/video/domain/VideoRepository.java
1. 기본 도메인들을 생성한다.
<br><br>
- close #130 
<br><br>
=> feat: 기본 도메인들을 생성한다

backend/src/main/resources/application.yml, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/resources/application.yml
```
/api 추가
```
<br><br>
- close #145 
<br><br>
=> feat: /api prefix 추가

backend/src/main/java/com/celuveat/common/config/WebConfig.java, backend/src/main/resources/application-dev.yml, backend/src/test/resources/application.yml
```
CORS 추가
```
<br><br>
- close #97 
<br><br>
=> feat: CORS 설정 추가 (#97)

.github/workflows/frontend-dev-cd.yml
fontend-dev-cd 파일 오타 수정
- close #156
=> fix: frontend cd 파일 오타 에러 수정

backend/src/main/java/com/celuveat/auth/infra/oauth/kakao/authcode/KakaoAuthCodeRequestUrlProvider.java, backend/src/main/java/com/celuveat/auth/infra/oauth/naver/authcode/NaverAuthCodeRequestUrlProvider.java, backend/src/main/resources/application-dev.yml
```
redirect_url 이 아니라 redirect_uri 로 명시해줘야해!
```
<br><br>
=> fix: oauth 버그 해결

backend/src/main/java/com/celuveat/common/PageResponse.java, backend/src/main/java/com/celuveat/common/query/DynamicQuery.java, backend/src/main/java/com/celuveat/common/query/DynamicQueryAssembler.java, backend/src/main/java/com/celuveat/common/query/DynamicQueryCondition.java, backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java, backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java, backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/java/com/celuveat/restaurant/application/RestaurantQueryServiceTest.java, backend/src/test/java/com/celuveat/restaurant/domain/RestaurantQueryRepositoryTest.java
```
음식점 조회 페이징 구현
```
<br><br>
- close #172 
<br><br>
=> feat: 음식점 조회 시 페이징을 적용한다

backend/src/main/java/com/celuveat/auth/presentation/OauthController.java, backend/src/main/java/com/celuveat/auth/presentation/SessionResponse.java, backend/src/main/java/com/celuveat/common/auth/AuthConstant.java, backend/src/main/java/com/celuveat/common/exception/ExceptionControllerAdvice.java, backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java, backend/src/main/java/com/celuveat/restaurant/presentation/dto/LocationSearchCondRequest.java, backend/src/main/java/com/celuveat/restaurant/presentation/dto/RestaurantSearchCondRequest.java, backend/src/test/java/com/celuveat/acceptance/common/AcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java
```
oauth 로그인 이후 세션 정보 반한
```
<br><br>
- close #187
- close #189 
<br><br>
=> feat: oauth 로그인 이후 세션 정보 반환

backend/src/main/java/com/celuveat/admin/application/AdminService.java, backend/src/main/java/com/celuveat/auth/application/OauthService.java, backend/src/main/java/com/celuveat/common/query/DynamicQueryAssembler.java, backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java, backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
```
코드 컨벤션에 맞게 수정했어!
그리고 동적 쿼리 생성하는 클래스를 굳이 객체 생성 할 필요가 없어보여서 static으로 바꿨고!
```
<br><br>
=> refactor: polishing

.github/workflows/backend-ci.yml, .github/workflows/backend-dev-cd.yml, .github/workflows/backend-prod-cd.yml
=> infra: 프로덕션용 CI/CD 워크플로우 작성

frontend/src/components/@common/Map/Overlay/Overlay.tsx, frontend/src/components/@common/Map/OverlayMarker.tsx
```
마커 호버시 해당 마커가 최상단으로 오지 않는 버그 수정
레스토랑 카드클릭시 꺼지는 버그 수정
```
<br><br>
- close #216 
<br><br>
=> bug: 지도 버그 수정

frontend/src/components/@common/Map/Overlay/Overlay.tsx, frontend/src/components/@common/Map/OverlayMarker.tsx, frontend/src/components/@common/Map/hooks/useMap.ts
```
지도 커스텀
```
<br><br>
- close #218 
<br><br>
=> design: 지도 커스텀

backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
```
count query에 distinct를 잘못 사용하고 있었어!
```
<br><br>
- close #222 
<br><br>
=> bug: 음식점 조회 시 페이징이 이상하게 되는 오류 수정

frontend/src/components/@common/Header/Header.tsx, frontend/src/components/@common/WaterMarkImage/WaterMarkImage.tsx, frontend/src/components/CategoryNavbar/CategoryNavbar.tsx, frontend/src/components/InfoDropDown/InfoDropDown.tsx, frontend/src/components/RestaurantCard/RestaurantCard.tsx
```
웹 접근성 적용
```
<br><br>
- close #220 
<br><br>
=> feat: 웹 접근성 적용 (#220)

.github/workflows/backend-ci.yml, .gitmodules
```
서브모듈 경로 변경
```
<br><br>
- close 
<br><br>
=> infra: git-submodule 경로 수정

.github/workflows/backend-ci.yml
```
develop backend2 CI 되도록 변경
```
<br><br>
- close #279 
<br><br>
=> chore: develop backend2 ci 되도록 설정

.github/workflows/frontend-dev-cd.yml
GitHub frontend - workflow 자동배포 문제 해결
<br><br>
- close #307
=> chore: GitHub frontend - workflow 자동배포 문제 해결

.github/workflows/frontend-dev-cd.yml, frontend/src/api/User/HttpUserInterceptor.ts, frontend/src/api/User/index.ts
=> fix: oauth 인증 안되는 오류 잡기

.github/workflows/backend-ci.yml
```
Gradle dependencies를 캐싱하여 CI 속도 향상
```
<br><br>
- close #302
=> infra: CI 캐싱 추가(backend)

.github/workflows/backend-dev-cd.yml, .github/workflows/backend-prod-cd.yml, backend/Dockerfile
```
워크플로우를 도커를 통해서 진행하도록 바꿨어~
블로그 참고해줘!
```
<br><br>
- close #273
<br><br>
=> infra: cd 과정을 도커를 통해 진행한다

backend/Dockerfile
```
```
<br><br>
- close 
<br><br>
=> hotfix: dockerfile 오류 수정 (#273)

backend/src/main/java/com/celuveat/auth/application/OauthService.java, backend/src/main/java/com/celuveat/auth/domain/authcode/AuthCodeRequestUrlProviderComposite.java, backend/src/main/java/com/celuveat/auth/domain/client/OauthMemberClient.java, backend/src/main/java/com/celuveat/auth/domain/client/OauthMemberClientComposite.java, backend/src/main/java/com/celuveat/auth/infra/oauth/google/client/GoogleMemberClient.java, backend/src/main/java/com/celuveat/auth/infra/oauth/kakao/KakaoOauthConfig.java, backend/src/main/java/com/celuveat/auth/infra/oauth/kakao/client/KakaoApiClient.java, backend/src/main/java/com/celuveat/auth/infra/oauth/kakao/client/KakaoMemberClient.java, backend/src/main/java/com/celuveat/auth/infra/oauth/kakao/dto/KakaoLogoutResponse.java, backend/src/main/java/com/celuveat/auth/infra/oauth/naver/client/NaverMemberClient.java, backend/src/main/java/com/celuveat/auth/presentation/AuthInterceptor.java, backend/src/main/java/com/celuveat/auth/presentation/OauthController.java, backend/src/main/java/com/celuveat/auth/presentation/dto/SessionResponse.java, backend/src/main/java/com/celuveat/common/log/request/RequestLogInterceptor.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantLikeAcceptanceTest.java
1. 일단 백엔드 상에선 포스트맨으로 로그아웃 확인했습니다.
하지만 로컬에서 프론트 띄어놓고 요청보내면 자꾸 쿠키가 안담깁니다..
그래서 개발 서버에서 테스트해보고자 PR 올립니다.
<br>
- close #301 
<br>
=> feat: 카카오 로그아웃 api 구현

frontend/src/components/@common/Header/Header.tsx, frontend/src/components/@common/Modal/ModalContent.tsx, frontend/src/components/LoginModalContent/LoginModalContent.tsx, frontend/src/utils/getToken.ts
=> feat: 로그인 창 반응형 구현하기

frontend/src/components/@common/Header/Header.tsx, frontend/src/components/@common/ImageCarousel/ImageCarousel.tsx, frontend/src/components/@common/Modal/ModalContent.tsx, frontend/src/components/@common/VideoCarousel/VideoCarousel.tsx, frontend/src/components/RestaurantDetailLikeButton/RestaurantDetailLikeButton.tsx, frontend/src/components/RestaurantDetailLikeButton/index.tsx, frontend/src/components/RestaurantReviewWrapper/RestaurantReviewWrapper.tsx, frontend/src/components/SuggestionButton/SuggestionButton.tsx, frontend/src/hooks/server/useToggleRestaurantLike.ts, frontend/src/pages/RestaurantDetail.tsx
```
완료 항목
- 상세페이지 반응형이 추가되었습니다.
- 정보 수정 제안 기능이 들어가있습니다.
비완료 항목
- 공유하기 기능은 아직 넣지 않았습니다. 추후 따로 이슈 파서 넣겠습니다.
에러
- 정보 수정 제안과 좋아요의 경우 요청 url은 정확하나 서버 측에서 500가 뜹니다. 참고 바랍니다.
추가)
푸만능은 특히, 좋아요 쪽 로직이 제대로 된 것인지 봐 주시면 좋겠습니다!
디자인 관련 의견 받습니다. 진짜 이이상 하기 힘드러요..🥺
```
- 아직입니다.
<br><br>
=> feat: 정보 수정 제안 공유하기 기능을 상세페이지에 추가 + 반응형 추가

backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java, backend/src/main/java/com/celuveat/restaurant/domain/RestaurantLikeRepository.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantLikeAcceptanceTest.java, backend/src/test/java/com/celuveat/restaurant/application/RestaurantQueryServiceTest.java
```
#324 위에 작업했습니다. commit 하나에요!
위시리스트 조회시 최근에 좋아요 누른게 배열의 앞으로 오도록 정렬 기능 추가했습니다.
```
based on #324 
<br/>
[리뷰할 커밋들](https://github.com/woowacourse-teams/2023-celuveat/pull/330/commits/3579031a1b7da7a9424c9f609b75a3242ac85fb0)
- https://github.com/woowacourse-teams/2023-celuveat/pull/330/commits/3579031a1b7da7a9424c9f609b75a3242ac85fb0
- close #325 
<br><br>
=> feat: 위시리스트 음식점 정렬 기능 추가

.github/workflows/frontend-ci.yml
```
npm, yarn 설치 파일 캐싱을 통한 CI 속도 향상
```
<br><br>
- close #302 
<br><br>
=> infra: CI 캐싱 추가(frontend)

backend/src/main/java/com/celuveat/video/application/dto/VideoWithCelebQueryResponse.java, backend/src/main/java/com/celuveat/video/domain/VideoQueryRepository.java, backend/src/main/java/com/celuveat/video/utils/VideoResponseUtils.java, backend/src/test/java/com/celuveat/acceptance/video/VideoAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/video/VideoAcceptanceTest.java, backend/src/test/java/com/celuveat/common/SeedData.java, backend/src/test/java/com/celuveat/video/utils/VideoResponseUtilsTest.java
```
youtube 영상 링크에서 식별자 값만 추출하여 응답
```
ex.
before
`youtubeVideoUrl : "www.youtube.com/v=a$sbbB12sva3"`
->
after 
`youtubeVideoKey : "a$sbbB12sva3"`
<br><br>
- close  #317 
<br><br>
=> refactor: 유튜브 영상 링크 변환하여 응답

.github/workflows/frontend-dev-cd.yml, .github/workflows/frontend-prod-cd.yml
=> fix: 프론트엔드 도커 도입으로 인한 이미지 파일 보이지 않는 오류 수정

.github/workflows/backend-dev-cd.yml, backend/build.gradle
```
Actuator 추가
```
<br><br>
- close #356 
<br><br>
=> infra: 모니터링 환경 구성

frontend/src/components/@common/Footer/Footer.tsx, frontend/src/components/CelebDropDown/CelebDropDown.tsx, frontend/src/components/RestaurantReviewItem/RestaurantReviewItem.tsx, frontend/src/components/RestaurantReviewWrapper/RestaurantReviewWrapper.tsx, frontend/src/components/RestaurantWishItem/RestaurantWishItem.tsx, frontend/src/components/ReviewForm/ReviewForm.tsx
```
아래 5가지 항목을 해결하였습니다.
- 위시리스트 상세페이지 연결
- 상세페이지 후기 없음을 리뷰 없음으로 수정
- 전체 셀럽 버튼 max-height 정해주기
- 리뷰 수정 삭제 로직 수정
- footer 인스타, 깃허브 링크 추가
```
=> bug: 각종 버그 수정

frontend/src/App.tsx, frontend/src/components/@common/LoginButton/LoginButton.tsx, frontend/src/components/@common/PopUp/PopUp.tsx, frontend/src/components/LoginModalContent/LoginModalContent.tsx, frontend/src/components/PopUpContainer/PopUpContainer.tsx, frontend/src/components/RestaurantCard/RestaurantCard.tsx, frontend/src/components/RestaurantWishItem/RestaurantWishItem.tsx, frontend/src/hooks/server/useDeleteUser.tsx, frontend/src/pages/RestaurantDetail.tsx
<br><br>
- close #373 
<br><br>
=> feat: 클립보드 복사 시 팝업창 뜨기 구현

frontend/src/App.tsx, frontend/src/components/@common/LoginButton/LoginButton.tsx, frontend/src/pages/OauthRedirectPage.tsx
- 창 동작 X
- 현재 url에서 모두 동작하도록 수정
- close #380
=> fix: 로그인 정상 동작하도록 고치기

backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryFacade.java, backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java, backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantDetailResponse.java, backend/src/main/java/com/celuveat/restaurant/domain/RestaurantLikeRepository.java, backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java, backend/src/test/java/com/celuveat/restaurant/application/RestaurantQueryFacadeTest.java, backend/src/test/java/com/celuveat/restaurant/application/RestaurantQueryServiceTest.java
```
음식점 상세 조회시 좋아요 여부 포함하여 응답
```
base on #370 
[추가된 커밋s](https://github.com/woowacourse-teams/2023-celuveat/pull/382/files/c0366d01fb1f4fd99f4c23e24d15e214548c3d84..1187698a92c3629e1c7da7ba3edde366a25f092f)
<br><br>
- close #377 
<br><br>
=> refactor: 음식점 상세 조회 시 좋아요 여부 포함응답

backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java, backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java, backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java, backend/src/test/java/com/celuveat/acceptance/common/AcceptanceTest.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java, backend/src/test/java/com/celuveat/restaurant/application/RestaurantQueryServiceTest.java, backend/src/test/java/com/celuveat/restaurant/domain/RestaurantQueryRepositoryTest.java
1. 주변 음식점 조회 응답에 좋아요 여부도 함께 응답합니다.
<br>
- close #367 
<br>
=> feat: 주변 음식점 조회 응답에 좋아요를 눌렀는 지에 대한 정보 추가

.github/workflows/release.yml, frontend/package.json
- git tag를 활용한 시맨틱 버저닝 구현 및 자동화 
1. MAJOR (주 버전): 기존 버전과 호환되지 않는 주요 변경사항이 있을 때 증가. 일반적으로 API의 큰 변경이나 하위 시스템의 구조적 변화를 의미하므로 주 버전이 변경되면 이전 버전과의 호환성이 보장되지 않을 수 있다.
2. MINOR (부 버전): 이전 버전과의 하위 호환성을 유지하면서 새로운 기능이 추가되거나 기존 기능이 변경될 때 증가. 주 버전 변경 없이 부 버전이 업데이트되면, 사용자는 새로운 기능을 사용하거나 개선된 기능을 기대할 수 있다.
3. PATCH (패치 버전): 기존 버전과의 하위 호환성을 유지하면서 버그 수정, 보안 패치, 작은 기능 개선 등과 같은 패치가 적용될 때 증가. 패치 버전은 일반적으로 중요한 변경이 없지만, 이전 버전보다 더 안정적인 버전임을 나타낸다.
따라서 
저희 프로젝트의 경우 
첫번째 버전임: `major: 0`, 
새로운 기능 추가 : `minor: 1`
별다른 버그 수정 X: `patch: 0` 으로 구성하였습니다!!
main에서 모든 기능이 동작되고 git tag를 설정, 해당 버저닝을 push하면 됩니다!!
[Automating Releases with Github](https://www.youtube.com/watch?v=-0vWW-ymlfw)
- close #371
=> Infra: 시맨틱 버저닝 yml 파일 구성 

frontend/src/components/@common/Header/Header.tsx, frontend/src/components/@common/LoginButton/LoginButton.tsx, frontend/src/hooks/server/useDeleteUser.tsx, frontend/src/pages/RestaurantDetail.tsx
=> fix: 로그인 로그아웃 동작 수정

frontend/src/components/RestaurantCard/RestaurantCard.tsx, frontend/src/index.tsx
```
좋아요 버튼 클릭시 버그 수정
```
<br><br>
- close #395 
<br><br>
=> bug: 좋아요 버튼 클릭시 버그 수정

frontend/src/components/RestaurantCard/RestaurantCard.tsx, frontend/src/hooks/server/useDeleteUser.tsx, frontend/src/pages/MainPage.tsx, frontend/src/pages/RestaurantDetail.tsx, frontend/src/pages/WishListPage.tsx
=> release: frontend v2

backend/src/main/java/com/celuveat/auth/presentation/LocalAuthController.java
```
프론트엔드 개발용 로그인 API 구현했습니다
```
<br><br>
- close #405 
<br><br>
=> feat: LocalAuthController 구현

backend/src/main/java/com/celuveat/restaurant/command/application/RestaurantReviewLikeService.java, backend/src/main/java/com/celuveat/restaurant/command/application/RestaurantReviewReportService.java, backend/src/main/java/com/celuveat/restaurant/command/domain/review/RestaurantReviewLike.java, backend/src/main/java/com/celuveat/restaurant/command/domain/review/RestaurantReviewLikeRepository.java, backend/src/main/java/com/celuveat/restaurant/command/domain/review/RestaurantReviewReport.java, backend/src/main/java/com/celuveat/restaurant/command/domain/review/RestaurantReviewReportRepository.java, backend/src/main/java/com/celuveat/restaurant/exception/RestaurantReviewExceptionType.java, backend/src/main/java/com/celuveat/restaurant/presentation/ReviewController.java, backend/src/main/java/com/celuveat/restaurant/presentation/dto/ReportReviewRequest.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewLikeAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewLikeAcceptanceTest.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewReportAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewReportAcceptanceTest.java, backend/src/test/java/com/celuveat/restaurant/command/application/RestaurantReviewLikeServiceTest.java, backend/src/test/java/com/celuveat/restaurant/command/application/RestaurantReviewReportServiceTest.java
```
리뷰 좋아요 기능 및 리뷰 신고 기능 구현했습니다.
```
```
CREATE TABLE `restaurant_review_like` (
`id` bigint NOT NULL AUTO_INCREMENT,
`restaurant_review_id` bigint NOT NULL,
`member_id` bigint NOT NULL,
`created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`),
UNIQUE KEY `uk_restaurant_review_member` (`restaurant_review_id`,`member_id`),
KEY `fk_review_like_member_id_from_oauth_member_id` (`member_id`),
CONSTRAINT `fk_review_like_member_id_from_oauth_member_id` FOREIGN KEY (`member_id`) REFERENCES `oauth_member` (`id`),
CONSTRAINT `fk_review_like_restaurant_review_id_from_restaurant_review_id` FOREIGN KEY (`restaurant_review_id`) REFERENCES `restaurant_review` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `restaurant_review_report` (
`id` …
```
=> feat: 리뷰 좋아요 기능 리뷰 신고 기능 구현

backend/src/main/java/com/celuveat/auth/presentation/LocalAuthController.java, backend/src/main/java/com/celuveat/auth/presentation/OauthController.java, backend/src/main/java/com/celuveat/auth/presentation/dto/SessionResponse.java, backend/src/test/java/com/celuveat/acceptance/common/AcceptanceSteps.java
```
Set-Cookie는 이미 잘 작동하고 있어서 responseBody만 제거했습니다!
```
<br><br>
- close #418 
<br><br>
=> refactor: responsebody로 주던 세션아이디 제거 및 set cookie 로 세션 아이디 설정해주는 기능 구현

backend/src/test/java/com/celuveat/auth/query/MemberQueryServiceTest.java, backend/src/test/java/com/celuveat/restaurant/query/RestaurantQueryFacadeTest.java, backend/src/test/java/com/celuveat/restaurant/query/RestaurantQueryServiceTest.java, backend/src/test/java/com/celuveat/restaurant/query/RestaurantReviewQueryServiceTest.java, backend/src/test/java/com/celuveat/restaurant/query/dao/RestaurantWithDistanceDaoTest.java
패키지 변경 작업이 test 패키지에도 이뤄지지 않은 부분 수정입니다 !!
<br>
- close #423 
<br>
=> rename: 패키지 변경사항을 test 패키지에 적용

backend/src/main/java/com/celuveat/auth/config/AuthConfig.java, backend/src/test/java/com/celuveat/acceptance/admin/AdminAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/auth/MemberAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/celeb/CelebAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/common/AcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantLikeAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewLikeAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewReportAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/video/VideoAcceptanceSteps.java, backend/src/test/resources/application.yml
```
/api 프리픽스 제거 & 서브모듈에도 반영하여 업데이트
```
<br><br>
- close #428 
<br><br>
=> feat: api prefix 제거하기

frontend/src/components/@common/Header/Header.tsx, frontend/src/components/@common/InfoButton/InfoButton.tsx, frontend/src/components/InfoDropDown/InfoDropDown.stories.tsx, frontend/src/components/InfoDropDown/InfoDropDown.tsx
- 로그인 여부 판단하는 방식 수정
- 기존 cookie 상태로 로그인 여부를 판단했는데 이제는 api 요청 여부에 따라 로그인 상태여부를 판단!
- close #443
=> refactor: api 요청 성공 여부에 따라 로그인 상태 수정

backend/src/main/java/com/celuveat/auth/presentation/OauthController.java
```
로그아웃 시 브라우저 쿠키 지워주는 기능 제거했습니다.
```
<br><br>
- close #446 
<br><br>
=> fix: 로그아웃 시 브라우저 쿠키 지워주는 기능 제거

frontend/package.json, frontend/public/index.html, frontend/src/components/@common/ImageGrid/ImageGrid.stories.tsx, frontend/src/components/@common/ImageGrid/ImageGrid.tsx, frontend/src/components/@common/Map/OverlayMarkerList.tsx, frontend/src/components/@common/Toast/Toast.tsx, frontend/src/components/@common/WaterMarkImage/WaterMarkImage.tsx, frontend/src/components/FilterSelectBox/FilterSelectBox.tsx, frontend/src/components/FilterSelectBox/index.tsx, frontend/src/components/LoginModalContent/LoginModalContent.tsx, frontend/src/components/RestaurantCardList/RestaurantCardList.tsx, frontend/src/constants/api.ts, frontend/src/hooks/server/useRestaurant.ts, frontend/src/hooks/store/useRestaurantsQueryStringState.ts, frontend/src/hooks/useOnClickOutside.ts, frontend/src/pages/MainPage.tsx, frontend/src/pages/MobileMainPage.tsx, frontend/src/pages/RestaurantDetail.tsx, frontend/src/utils/getQueryString.ts
```
인기순 및 거리순 필터링 기능
```
<br><br>
- close #385
<br><br>
=> feat: 인기순 및 거리순 필터링 기능 및 버그 수정

backend/src/main/java/com/celuveat/restaurant/command/domain/review/RestaurantReviewRepository.java, backend/src/main/java/com/celuveat/video/query/dao/VideoWithCelebQueryResponseDao.java
```
N + 1 발생 쿼리 수정
불필요한 join 제거
```
=> Refactor: 쿼리 개선

frontend/src/components/@common/Modal/ModalContent.tsx, frontend/src/components/RestaurantReviewItem/RestaurantReviewItem.tsx, frontend/src/components/RestaurantReviewWrapper/RestaurantReviewWrapper.tsx, frontend/src/components/RestaurantWishItem/RestaurantWishItem.tsx, frontend/src/components/ReviewForm/ReviewForm.tsx, frontend/src/hooks/context/ReviewModalProvider.tsx, frontend/src/pages/RestaurantDetail.tsx, frontend/src/styles/reset.ts
```
리뷰작성 디자인 수정 및 기타 버그 수정
```
<br><br>
- close #467 
<br><br>
=> feat: 리뷰작성 디자인 수정 및 기타 버그 수정

frontend/src/components/@common/Map/OverlayMarker.tsx, frontend/src/components/@common/Map/hooks/useMap.ts, frontend/src/components/RestaurantCardList/RestaurantCardList.tsx, frontend/src/components/SearchBar/SearchBar.tsx
```
옵션관련 ux 개선
```
<br><br>
- close #473 
<br><br>
=> bug: 옵션관련 ux 개선

backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantImageQueryResponse.java
=> feat: 음식점 이미지 반환 시 .jpeg 떼고 인코딩하는부분 수정

frontend/.webpack/webpack.config.js, frontend/src/api/restaurant.ts, frontend/src/assets/fonts/font.css, frontend/src/pages/RestaurantDetail.tsx, frontend/src/router/Root.tsx
=> fix: 웹 폰트 로드 전 대체제 넣기 

backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSimpleResponseDao.java, backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantImageQueryResponse.java
=> release: 백엔드 v3.2

frontend/src/api/restaurant.ts
- 로그인 시 음식점 좋아요하는 기능 제거
- close #513
=> fix: conflict 충돌로 인한 코드 오류 수정

frontend/src/components/@common/LoginButton/LoginButton.tsx, frontend/src/components/@common/LoginErrorHandleComponent/LoginErrorHandleComponent.tsx, frontend/src/components/BottomNavBar/UserButton.tsx, frontend/src/hooks/store/usePathnameState.ts, frontend/src/mocks/handler/mainPage/handler.ts, frontend/src/pages/OauthRedirectPage.tsx
- 로그인 시 이전 페이지로 다시 가게 하기
- msw 코드 home으로 가게 하는 로직 제거
- navigate 상태를 넘겨줌으로써 이전 페이지 상태 전달
- sessionStorage를 사용 
- close #518
=> fix: 로그인 시 이전 페이지로 다시 가게 하기

backend/src/main/java/com/celuveat/common/exception/ExceptionControllerAdvice.java, backend/src/main/java/com/celuveat/restaurant/presentation/dto/LocationSearchCondRequest.java, backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantWithDistanceDao.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantLikeAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantLikeAcceptanceTest.java, backend/src/test/java/com/celuveat/restaurant/fixture/LocationFixture.java
음식점 전체 조회 시 위경도 조건을 받지 않으면 대한민국 전체지도로 검색하도록 함
이 과정에서 테스트코드가 애매해지는 부분이 있어서 살짝 수정했어!
추가로 Validator 클래스 위치를 패키지 따로 파서 구현할까도 고민했는데,
일단 특정 Reuqest Dto에 specific한 검증이라 해당 클래스 내부에 검증기를 구현했어!
<br><br>
- close #536 
<br><br>
=> feat: 위도 경도를 필수 조건으로 받지 않도록 변경한다

backend/src/main/java/com/celuveat/restaurant/command/domain/Restaurant.java, backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSearchResponseDao.java, backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantDetailResponse.java, backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantSearchResponse.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantLikeAcceptanceTest.java, backend/src/test/java/com/celuveat/common/SeedData.java, backend/src/test/java/com/celuveat/restaurant/query/RestaurantQueryServiceTest.java
```
음식점 조회 응답에 평균 평점 정보를 포함하여 응답
```
<br><br>
- #550, #549 위에서 작업하였습니다.
- close #552
=> refactor: 음식점 조회시 평점 평균 포함하여 응답

backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java, backend/src/main/java/com/celuveat/restaurant/query/RestaurantQueryService.java, backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSearchResponseDao.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java, backend/src/test/java/com/celuveat/restaurant/query/dao/RestaurantSearchResponseDaoTest.java
```
최근 업데이트된 음식점 조회 api 구현
```
[리뷰 범위](https://github.com/woowacourse-teams/2023-celuveat/pull/561/files/e1764a6beb8410e72a43ece5e88aa57ac85e872b..0aa5f207aa83fafbedbbaa2b497c712d2df417df)
<br><br>
테스트 변경될 사항 고려하여 개선이 필요한 테스트는 TODO 코멘트로 남겨두었습니다.
- close #559
=> feat: 최근 업데이트된 음식점 조회 api

frontend/package.json, frontend/public/index.html, frontend/src/pages/MainPage.tsx, frontend/src/pages/RestaurantDetailPage/RestaurantDetail.tsx, frontend/src/router/Root.tsx, frontend/yarn.lock
- 상세페이지 메타태그 추가, 공유 시 미리보기 기능 구현
- close 567
=> feat: 상세페이지 메타태그 추가 

frontend/src/components/ReviewForm/ReviewForm.tsx
- create 요청 시 명세 수정으로 인한 코드 변경이 안된 에러 해결
- close #573
=> fix: api 명세 수정으로 인한 코드 수정(#573)

backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantByAddressResponse.java, backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantSearchResponse.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java
=> fix: 음식점 조회시 좋아요 여부 필드이름 api 문서에 맞게 수정

frontend/src/components/BottomNavBar/BottomNavBar.tsx
- 모바일의 로그인 페이지에서도 로그인 했을 경우 이전 페이지로 돌아가도록 구현
signup페이지로 이동할때는 이전 페이지에 대한 상태를 꼭 전달해주세요!!
- close #579
=> fix: 모바일 로그인 시 로그인 페이지가 나오는 에러

frontend/src/hooks/server/useRestaurantReview.ts
- 낙관적 업데이트 로직 수정으로 인한 에러 해결
- 추천하면 -1, 추천 취소하면 + 1을 해서 발생하는 에러;;
<br><br>
- close #581 
<br><br>
=> fix: 낙관적 업데이트로 인해 깜빡이는 오류 

backend/src/main/java/com/celuveat/restaurant/presentation/MainPageController.java, backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSearchWithoutDistanceQueryResponseDao.java, backend/src/main/java/com/celuveat/restaurant/query/dto/LikedRestaurantQueryResponse.java, backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java, backend/src/test/java/com/celuveat/auth/query/dao/OauthMemberProfileResponseDaoTest.java, backend/src/test/java/com/celuveat/celeb/query/dao/CelebQueryResponseDaoTest.java, backend/src/test/java/com/celuveat/common/DaoTest.java, backend/src/test/java/com/celuveat/restaurant/query/RestaurantQueryServiceTest.java, backend/src/test/java/com/celuveat/restaurant/query/dao/LikedRestaurantQueryResponseDaoTest.java, backend/src/test/java/com/celuveat/restaurant/query/dao/RestaurantDetailQueryResponseDaoTest.java, backend/src/test/java/com/celuveat/restaurant/query/dao/RestaurantReviewsQueryResponseDaoTest.java, backend/src/test/java/com/celuveat/restaurant/query/dao/RestaurantSearchQueryResponseDaoTest.java, backend/src/test/java/com/celuveat/restaurant/query/dao/RestaurantSearchWithoutDistanceQueryResponseDaoTest.java, backend/src/test/java/com/celuveat/video/query/dao/VideoQueryResponseDaoTest.java
```
API URL과 위시리스트 응답을 변경하였고, 노션 API 문서에 업데이트 해뒀습니다.
```
<br><br>
- close #592 
<br><br>
=> feat: 메인 페이지 api url 수정 위시리스트 api 응답 변경

frontend/src/components/RestaurantReviewItem/RestaurantReviewItem.tsx, frontend/src/components/ReviewForm/ReviewForm.tsx
- 리뷰 작성 시 파일 네임 버그 수정
- 리뷰 아이템 ui 수정
<br><br>
- close #599
=> fix: 리뷰 작성 시 파일 네임 버그 수정 및 리뷰 아이템 ui 수정

frontend/src/api/restaurant.ts, frontend/src/pages/MainPage.tsx, frontend/src/pages/MobileMapPage.tsx, frontend/src/pages/UpdatedRestaurantPage.tsx, frontend/src/router/Root.tsx, frontend/src/router/Router.tsx
```
최근 등록한 음식점 페이지 구현
```
<br><br>
- close #612 
<br><br>
=> feat: 최근 등록한 음식점 페이지 구현

frontend/src/components/RestaurantReviewItem/RestaurantReviewItem.tsx, frontend/src/components/RestaurantReviewList/RestaurantReviewList.stories.tsx, frontend/src/components/ReviewForm/ReviewDeleteForm.tsx, frontend/src/components/ReviewForm/ReviewForm.tsx, frontend/src/components/ReviewForm/ReviewReportForm.tsx, frontend/src/components/ReviewImageForm/ReviewImageForm.stories.tsx, frontend/src/components/ReviewImageForm/ReviewImageForm.tsx, frontend/src/hooks/server/useRestaurantReview.ts, frontend/src/mocks/data/reviews.ts, frontend/src/mocks/handler/detailPage/handler.ts, frontend/src/mocks/utils.ts, frontend/src/utils/image.ts
<br><br>
- close #606 
<br><br>
=> fix: 리뷰 관련 버그 수정

backend/src/main/java/com/celuveat/admin/command/application/AdminService.java, backend/src/main/java/com/celuveat/admin/exception/AdminExceptionType.java, backend/src/main/java/com/celuveat/admin/presentation/dto/SaveDataRequest.java, backend/src/main/java/com/celuveat/video/command/domain/VideoRepository.java, backend/src/test/java/com/celuveat/acceptance/admin/AdminAcceptanceSteps.java, backend/src/test/java/com/celuveat/acceptance/admin/AdminAcceptanceTest.java, backend/src/test/java/com/celuveat/acceptance/common/AcceptanceTest.java, backend/src/test/java/com/celuveat/admin/command/application/AdminServiceTest.java
1. 데이터 저장 관련 테스트 수정
2. 부족한 구현 사항 구현
<br>
- close #621
=> test: adminServiceTest 수정 및 부족한 구현 사항 구현

.github/workflows/backend-dev-cd.yml, backend/src/main/java/com/celuveat/common/infra/aws/AwsS3ImageUploadClient.java, backend/src/main/java/com/celuveat/event/command/application/EventImageNameGenerator.java, backend/src/main/java/com/celuveat/event/command/application/EventImageUploadClient.java, backend/src/main/java/com/celuveat/event/command/application/EventService.java, backend/src/main/java/com/celuveat/event/command/application/dto/SubmitCommand.java, backend/src/main/java/com/celuveat/event/command/domain/EventImage.java, backend/src/main/java/com/celuveat/event/command/domain/EventImageRepository.java, backend/src/main/java/com/celuveat/event/config/EventAsyncConfig.java, backend/src/main/java/com/celuveat/event/config/EventAwsS3Property.java, backend/src/main/java/com/celuveat/event/presentation/EventController.java, backend/src/main/java/com/celuveat/event/presentation/dto/SubmitEventImageRequest.java, backend/src/main/resources/application-local.yml, backend/src/test/java/com/celuveat/event/command/application/EventImageNameGeneratorTest.java, backend/src/test/java/com/celuveat/event/command/application/EventServiceTest.java
```
이벤트를 위한 API 작성했습니당.
```
```sql
create table event_image (
created_date timestamp(6),
id bigint generated by default as identity,
image_name varchar(255) not null,
instagram_id varchar(255) not null,
restaurant_name varchar(255) not null,
primary key (id)
)
```
<br><br>
- close #622 
<br><br>
=> feat: 이벤트를 위한 api를 작성한다

frontend/src/api/apiClient.ts, frontend/src/api/event.ts, frontend/src/components/MiniRestaurantCard/MiniRestaurantCard.tsx, frontend/src/components/ReviewImageForm/ReviewImageForm.tsx, frontend/src/constants/carouselSettings.tsx, frontend/src/constants/celeb.ts, frontend/src/constants/recommendedRegion.ts, frontend/src/constants/restaurantCategory.tsx, frontend/src/pages/EventDetailPage.tsx, frontend/src/pages/EventFormPage.tsx, frontend/src/pages/EventPageDetail.tsx, frontend/src/pages/MainPage.tsx, frontend/src/pages/MainPage/BannerSlider.tsx, frontend/src/pages/RestaurantDetailPage/Header.tsx, frontend/src/pages/RestaurantDetailPage/NearByRestaurantCardList.tsx, frontend/src/router/Router.tsx
```
이벤트 배너 및 이벤트 페이지 구현
```
<br><br>
- close #635 
<br><br>
=> feat: 이벤트 배너 및 이벤트 페이지 구현 (#635)

backend/src/main/java/com/celuveat/restaurant/command/application/RestaurantReviewService.java, backend/src/main/java/com/celuveat/restaurant/command/domain/review/RestaurantReviewReportRepository.java, backend/src/test/java/com/celuveat/restaurant/command/application/RestaurantReviewServiceTest.java
리뷰 신고 존재하면 DB 제약 조건 때문에 리뷰가 삭제 되지 않는 오류 수정
=> hotfix: 리뷰 신고 존재 시 리뷰 삭제 되지 않는 오류 수정

frontend/src/components/@common/Map/Marker/Marker.tsx, frontend/src/components/RestaurantDetailLikeButton/RestaurantDetailLikeButton.tsx, frontend/src/pages/RestaurantDetailPage/DetailInformation.tsx, frontend/src/pages/RestaurantDetailPage/Header.tsx, frontend/src/pages/RestaurantDetailPage/ImageViewer.tsx, frontend/src/pages/RestaurantDetailPage/LinkContainer.tsx, frontend/src/pages/RestaurantDetailPage/MapSection.tsx, frontend/src/pages/RestaurantDetailPage/RestaurantDetail.tsx, frontend/src/pages/RestaurantDetailPage/RestaurantVideoList.tsx
``` 
음식점 상세페이지에 useQueries 처리 및 관심사 분리를 통해 waterfall로 인한 로딩 지연 문제를 해결하였습니다.
```
<br><br>
- close #648 
<br><br>
=> refactor: 음식점 상세페이지 usequeries 처리

.github/workflows/frontend-dev-cd.yml
```
EC2에서 AWS CLI를 통해 develop-frontend push 시 자동으로 S3로 배포되도록 파이프라인을 구축하였습니다.
action에 대한 설명은 action name을 통해 참고해주시길 바랍니다.
prod cd의 경우 s3폴더구조를 수정할 필요가 있어보여 함께 논의후에 구현진행하겠습니다.
```
<br><br>
- close #655 
<br><br>
=> infra: 프론트엔드 dev cd 파이프라인 구축 (#655)

frontend/src/components/@common/WaterMarkImage/WaterMarkImage.tsx
```
이미지 로드동안 스켈레톤 유지시키기
```
<br><br>
- close #662 
<br><br>
=> fix: 이미지 로드동안 스켈레톤 유지시키기

frontend/package.json, frontend/yarn.lock
```
string-width 버전 고정을 통해 storybook 및 cypress 문제를 해결하였습니다.
```
<br><br>
- close #684
<br><br>
=> hotfix: string-width version 고정
