woowacourse-teams/2023-celuveat

- frontend/.eslintrc
- frontend/src/components/@common/Button/TextButton.tsx
- frontend/src/components/@common/ProfileImage/ProfileImage.tsx
- frontend/src/components/RestaurantCard/RestaurantCard.tsx
다음과 같은 lint 를 off 하였습니다.
- defaultProps를 optional한 값에 꼭 명시해야되는 룰
- props를 spreading 문법으로 표현하지 못하게 하는 룰 (ex. ...props)
> refactor: 일부 lint 규칙 제거

- frontend/package.json
#114 
__storybook/@react 라이브러리를 devDependencies에 두어서 해결 하였습니다.__
- close #114
> 114 bug storybookreact 가 devdependencies dependencies 둘 다 적혀져있는 오류

- backend/src/main/java/com/celuveat/celeb/presentation/CelebController.java
- backend/src/main/java/com/celuveat/celeb/presentation/response/FindAllCelebResponse.java
- backend/src/main/java/com/celuveat/common/config/WebConfig.java
- backend/src/main/java/com/celuveat/common/util/DynamicJpqlUtil.java
- backend/src/main/java/com/celuveat/common/util/DynamicQueryUtil.java
- backend/src/main/java/com/celuveat/common/util/StringUtil.java
- backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
- backend/src/main/java/com/celuveat/restaurant/application/dto/CelebQueryResponse.java
- backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantImageQueryResponse.java
- backend/src/main/java/com/celuveat/restaurant/domain/RestaurantImageRepository.java
- backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
- backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
- backend/src/main/java/com/celuveat/video/domain/VideoRepository.java
- backend/src/test/java/com/celuveat/acceptance/celeb/CelebAcceptanceSteps.java
- backend/src/test/java/com/celuveat/acceptance/celeb/CelebAcceptanceTest.java
- backend/src/test/java/com/celuveat/acceptance/common/AcceptanceSteps.java
- backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java
- backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java
- backend/src/test/java/com/celuveat/restaurant/application/RestaurantQueryServiceTest.java
- backend/src/test/java/com/celuveat/restaurant/domain/RestaurantQueryRepositoryTest.java
- backend/src/test/java/com/celuveat/restaurant/fixture/RestaurantFixture.java
```
셀럽 전체 조회 기능 구현
셀럽 ID와 카테고리, 음식점 이름으로 음식점 검색 API 작성
```
<br><br>
- close #147 
<br><br>
```
아직 동적쿼리가 많이 필요한것도 아니고, 간단해서 JPQL로 동적쿼리 만들어서 했어~
QueryDSL이 더 편할 것 같은데, 배우는 데 시간도 걸릴 것 같구!
```
> feat: 셀럽 ID와 카테고리, 음식점이름으로 음식점 검색 API 작성

- frontend/.eslintrc
- frontend/fileTransformer.js
- frontend/jest.config.js
`import * from ~.png` 등의 구문이 포함되어 있는 컴포넌트를 테스트 시 발생하던 에러 해결
- close #154
> fix: react testing library 사용 시 에러 이미지 import 시 에러 발생

- backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
- backend/src/main/java/com/celuveat/restaurant/application/dto/RestaurantQueryResponse.java
- backend/src/main/java/com/celuveat/restaurant/domain/Coordinate.java
- backend/src/main/java/com/celuveat/restaurant/domain/RestaurantImageRepository.java
- backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
- backend/src/main/java/com/celuveat/restaurant/domain/dto/RestaurantWithDistance.java
- backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
- backend/src/main/java/com/celuveat/video/domain/VideoRepository.java
- backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java
- backend/src/test/java/com/celuveat/common/SeedData.java
- backend/src/test/java/com/celuveat/restaurant/application/RestaurantQueryServiceTest.java
- backend/src/test/java/com/celuveat/restaurant/domain/CoordinateTest.java
- backend/src/test/java/com/celuveat/restaurant/domain/RestaurantQueryRepositoryTest.java
- backend/src/test/java/com/celuveat/restaurant/fixture/LocationFixture.java
```
음식점 조회 시 거리를 기준으로 오름차순 정렬하여 응답한다
```
<br><br>
- close 
#194 
<br><br>
> feat: 거리순으로 음식점을 정렬해서 응답

- backend/src/main/java/com/celuveat/admin/application/AdminService.java
- backend/src/main/java/com/celuveat/admin/exception/AdminExceptionType.java
- backend/src/main/java/com/celuveat/admin/presentation/AdminController.java
- backend/src/main/java/com/celuveat/admin/presentation/dto/SaveCelebRequest.java
- backend/src/test/java/com/celuveat/acceptance/admin/AdminAcceptanceSteps.java
- backend/src/test/java/com/celuveat/acceptance/admin/AdminAcceptanceTest.java
- backend/src/test/java/com/celuveat/admin/application/AdminServiceTest.java
- `이름, 채널이름, 프로필사진URL` 형식으로 셀럽을 저장할 수 있는 API 구현
- AdminController에 `@Profile`을 추가해, 운영 환경에서는 api를 개방하지 않도록 함.
<br>
- close #286
<br>
> feat: 셀럽 저장 api 구현

- backend/src/main/java/com/celuveat/restaurant/application/RestaurantQueryService.java
- backend/src/main/java/com/celuveat/restaurant/domain/RestaurantQueryRepository.java
- backend/src/main/java/com/celuveat/restaurant/presentation/RestaurantController.java
- backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceSteps.java
- backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantAcceptanceTest.java
- backend/src/test/java/com/celuveat/restaurant/application/RestaurantQueryServiceTest.java
- backend/src/test/java/com/celuveat/restaurant/domain/RestaurantQueryRepositoryTest.java
1. **특정 음식점의 ID**와 **Optional한 값의 distance**(단위: m)를 받아, **해당 음식점 주변의 모든 음식점을 조회**하는 기능입니다.
2. **distance**는 **쿼리  파라미터**로 요청되며, 값이 입력되지 않으면 **default 3km**로 설정했습니다.
3. **페이징**으로 구현했으며, **한 페이지의 사이즈는 4**입니다.
4. 음식점들을 **거리순으로 정렬**하여 반환합니다.
<br>
- close #280  
<br>
> feat: 주변 음식점 조회 api 구현

- backend/src/main/java/com/celuveat/celeb/exception/CelebException.java
- backend/src/main/java/com/celuveat/celeb/exception/CelebExceptionType.java
- backend/src/main/java/com/celuveat/video/application/VideoQueryService.java
- backend/src/main/java/com/celuveat/video/application/dto/VideoWithCelebQueryResponse.java
- backend/src/main/java/com/celuveat/video/domain/VideoQueryRepository.java
- backend/src/main/java/com/celuveat/video/presentation/VideoController.java
- backend/src/main/java/com/celuveat/video/presentation/dto/VideoSearchCondRequest.java
- backend/src/test/java/com/celuveat/acceptance/video/VideoAcceptanceSteps.java
- backend/src/test/java/com/celuveat/acceptance/video/VideoAcceptanceTest.java
- backend/src/test/java/com/celuveat/common/SeedData.java
- backend/src/test/java/com/celuveat/video/application/VideoQueryServiceTest.java
- backend/src/test/java/com/celuveat/video/domain/VideoQueryRepositoryTest.java
```
`VideoSearchCond` 를 통해 조건(음식점, 셀럽)에 따른 영상 조회 API 구현
```
<br>
- #282 와 관련된 [commits](https://github.com/woowacourse-teams/2023-celuveat/pull/299/files/69d59dc451a20461fbf591a6dc67f263e8231532..10a75212acfc86d5cad778a398d16b66785f6dbc)
-> note: #292 Merge 이후 rebase가 필요합니다.
- close #282
> feat: 음식점 및 셀럽으로 영상 조회 api 구현

- frontend/.storybook/preview.tsx
- frontend/src/@types/api.types.ts
- frontend/src/App.tsx
- frontend/src/api/User/index.ts
- frontend/src/api/oauth.ts
- frontend/src/components/@common/Button/TextButton.tsx
- frontend/src/components/@common/Header/Header.tsx
- frontend/src/components/LoginPageUI/LoginPageUI.stories.tsx
- frontend/src/components/LoginPageUI/LoginPageUI.tsx
- frontend/src/components/LoginPageUI/index.tsx
- frontend/src/components/RestaurantWishItem/RestaurantWishItem.tsx
- frontend/src/components/WithdrawalModalContent/WithdrawalModalContent.stories.tsx
- frontend/src/components/WithdrawalModalContent/WithdrawalModalContent.tsx
- frontend/src/components/WithdrawalModalContent/index.tsx
- frontend/src/constants/options.ts
- frontend/src/hooks/server/useDeleteUser.tsx
- frontend/src/hooks/server/useToggleLikeNotUpdate.ts
- frontend/src/mocks/browser.ts
- frontend/src/mocks/fixtures.ts
- frontend/src/mocks/handlers.ts
- frontend/src/pages/SignUpPage.tsx
- frontend/src/pages/WithdrawalPage.tsx
- close #342 #341 #343 
<br><br>
> feat: 회원 탈퇴 기능 및 위시리스트 명세에 맞게 기능 수정

- backend/src/main/java/com/celuveat/auth/application/OauthService.java
- backend/src/main/java/com/celuveat/auth/domain/OauthId.java
- backend/src/main/java/com/celuveat/auth/domain/OauthMember.java
- backend/src/main/java/com/celuveat/auth/domain/client/OauthMemberClient.java
- backend/src/main/java/com/celuveat/auth/domain/client/OauthMemberClientComposite.java
- backend/src/main/java/com/celuveat/auth/infra/oauth/google/client/GoogleMemberClient.java
- backend/src/main/java/com/celuveat/auth/infra/oauth/kakao/client/KakaoApiClient.java
- backend/src/main/java/com/celuveat/auth/infra/oauth/kakao/client/KakaoMemberClient.java
- backend/src/main/java/com/celuveat/auth/infra/oauth/kakao/dto/KakaoLogoutResponse.java
- backend/src/main/java/com/celuveat/auth/infra/oauth/naver/client/NaverMemberClient.java
- backend/src/main/java/com/celuveat/auth/presentation/OauthController.java
1. 카카오 로그아웃 API 기능 관련 메서드 리팩터링
- 불필요한 반환 제거
- 개행 스타일 변경
- 혼란을 야기할 변수명 수정
2. 카카오 회원탈퇴 API 구현
필드명 변경되었습니다.
`oauth_member` 테이블의 `oauth_server_id`를 `oauth_server_member_id`로 변경되었습니다.
<br>
- close #300 
- #301 
<br>
> feat: 카카오 oauth 회원탈퇴 api 구현

- backend/src/main/java/com/celuveat/common/log/context/AuthenticatedLogId.java
```
회원 요청에 대한 로깅을 구분할 수 있도록 요청 단위의 식별자를 부여했습니다.
```
> hotfix: 회원 요청 로깅 분리

- backend/src/main/java/com/celuveat/admin/application/AdminService.java
- backend/src/main/java/com/celuveat/admin/exception/AdminExceptionType.java
- backend/src/main/java/com/celuveat/admin/presentation/AdminController.java
- backend/src/main/java/com/celuveat/admin/presentation/dto/SaveDataRequest.java
- backend/src/main/java/com/celuveat/restaurant/domain/SocialMedia.java
- backend/src/test/java/com/celuveat/acceptance/admin/AdminAcceptanceSteps.java
- backend/src/test/java/com/celuveat/acceptance/admin/AdminAcceptanceTest.java
- backend/src/test/java/com/celuveat/admin/application/AdminServiceTest.java
- 데이터 취합 폼 변경에 대응했습니다.
- 데이터 저장 기능을 고도화 했습니다.
- 취합 폼에서 인스타 아이디를 Optional하게 입력받을 수 있도록 했습니다. 
- 입력 X -> `RestaurantImage`의 `author` = `유튜브 채널 이름`, `socialMedia` = `YOUTUBE` 저장
- 입력 O -> `RestaurantImage`의 `author` = `인스타 아이디`, `socialMedia` = `INSTAGRAM` 저장
- 제레미의 요청에 따라 유튜브 영상도 한번에 2개 이상 입력받을 수 있도록 했습니다.
- 이때, 유튜브 영상 링크와 업로드 날짜의 순서와 개수가 맞아야합니다.
- 개수가 맞지 않으면 예외가 발생하도록 했습니다.
<br>
- close #399
> feat: 데이터 저장 기능 고도화

- backend/src/main/java/com/celuveat/auth/presentation/OauthController.java
```
서브 모듈에 쿠키 기본 max-age, path 설정 했습니다. 브라우저 꺼져도 만료되기 전까지 지워지지 않습니다.
로그아웃시 max-age: 0 으로 Set-Cookie 헤더 내려서 브라우저 쿠키 지우도록 했습니다.
Http-Only 설정은 false로 해야 프론트에서 쿠키를 확인할 수 있어서 추가했습니다.
```
<br><br>
- close #427 
<br><br>
> feat: 브라우저 꺼져도 쿠키 안사라지게 만들기

- frontend/src/components/InfoDropDown/InfoDropDown.tsx
- safari에서 infodropdown onblur이벤트가 먹히지 않는 에러
에러 상황
https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/03c0d4b8-2684-49b4-b682-33433c25cbf6
해결
https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/61a28307-22ce-41b0-9c2c-158f91226b90
> fix: safari에서 infodropdown onblur이벤트가 먹히지 않는 에러

- backend/src/main/java/com/celuveat/restaurant/command/application/RestaurantLikeService.java
- backend/src/main/java/com/celuveat/restaurant/command/domain/Restaurant.java
- backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantSimpleResponseDao.java
- backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantWithDistanceDao.java
- backend/src/main/java/com/celuveat/restaurant/query/dao/support/RestaurantLikeQueryDaoSupport.java
- backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantSimpleResponse.java
- backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantWithDistance.java
- backend/src/test/java/com/celuveat/common/SeedData.java
- backend/src/test/java/com/celuveat/restaurant/query/RestaurantQueryServiceTest.java
- backend/src/test/java/com/celuveat/restaurant/query/dao/RestaurantWithDistanceDaoTest.java
음식점 조회 시 발생하는 서브쿼리를 분리했습니다.
이때 좋아요 수의 경우 역정규화를 통해 개선했습니다.
이로 인해 동시성 문제가 발생할 수 있으며, 이를 처리하기 위한 이슈를 생성해 두었습니다.
테이블을 수정하는 SQL은 다음과 같습니다.
```sql
ALTER TABLE restaurant ADD like_count INT;
UPDATE restaurant SET like_count = (
SELECT COUNT(*)
FROM restaurant_like
WHERE restaurant_id = restaurant.id
);
```
추가로 인덱스도 걸어주어야 하며, 이 역시 이슈로 따로 파두었습니다.
PS - 도기 테스트코드 리팩토링 화이팅...
<br><br>
- close #517 
<br><br>
> refactor: 서브쿼리 분리를 통해 쿼리를 개선한다

- frontend/src/api/restaurant.ts
- frontend/src/api/user.ts
- frontend/src/components/@common/Header/Header.tsx
- frontend/src/components/@common/LoginButton/LoginButton.tsx
- frontend/src/components/BottomNavBar/FilterOptionsModal.tsx
- frontend/src/components/BottomNavBar/UserButton.tsx
- frontend/src/components/CategoryNavbar/CategoryNavbar.tsx
- frontend/src/constants/url.ts
- frontend/src/hooks/server/useAuth.ts
- frontend/src/pages/OauthRedirectPage.tsx
- frontend/src/utils/compare.ts
- frontend/src/utils/getQueryString.ts
- 로그인 리다이렉트 시 query 구문 전달하지 않는 에러 해결
- ex. 상세페이지에 ?celeb=23 이 아니고 null값이 들어갔음
-  useAuth 관련 훅 구현
- 모바일 로그아웃 버튼 클릭 시 두번 눌러야 적용되는 버그 해결
```tsx
useEffect(() => {
if (process.env.NODE_ENV === 'development') {
fetch('https://d.api.celuveat.com/login/local?id=abc').then(response => {
if (!response.ok) {
throw new Error('Network response was not ok');
}
navigator(path);
});
}
}, []);
```
위의 코드를 삭제해도 jessionId에 쿠키가 담겨서 로그인 로직이 잘 수행되서 제거했습니다!! 
-> 오도가 https://d.api.celuveat.com/login/local?id=abc에 접속만 해도 브라우저에 쿠키가 저장되게 구현을 해서 굳이 위의 코드가 더 필요하지 않다고 판단해서 제거했어요!!
- close #527
<br><br>
> bug: 로그인 시 이전 페이지로 리다이렉트 중 관련 에러 + 로그아웃 버튼 클릭 관련 에러 해결

- backend/src/main/java/com/celuveat/restaurant/command/application/RestaurantReviewLikeService.java
- backend/src/main/java/com/celuveat/restaurant/command/application/RestaurantReviewService.java
- backend/src/main/java/com/celuveat/restaurant/command/application/dto/SaveReviewRequestCommand.java
- backend/src/main/java/com/celuveat/restaurant/command/domain/Restaurant.java
- backend/src/main/java/com/celuveat/restaurant/command/domain/review/RestaurantReview.java
- backend/src/main/java/com/celuveat/restaurant/command/domain/review/RestaurantReviewRepository.java
- backend/src/main/java/com/celuveat/restaurant/presentation/ReviewController.java
- backend/src/main/java/com/celuveat/restaurant/query/RestaurantReviewQueryService.java
- backend/src/main/java/com/celuveat/restaurant/query/dao/RestaurantReviewQueryResponseDao.java
- backend/src/main/java/com/celuveat/restaurant/query/dao/support/RestaurantReviewImageQueryDaoSupport.java
- backend/src/main/java/com/celuveat/restaurant/query/dao/support/RestaurantReviewLikeQueryDaoSupport.java
- backend/src/main/java/com/celuveat/restaurant/query/dao/support/RestaurantReviewQueryDaoSupport.java
- backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantReviewQueryResponse.java
- backend/src/main/java/com/celuveat/restaurant/query/dto/RestaurantReviewSingleResponse.java
- backend/src/test/java/com/celuveat/acceptance/common/AcceptanceTest.java
- backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewAcceptanceSteps.java
- backend/src/test/java/com/celuveat/acceptance/restaurant/RestaurantReviewAcceptanceTest.java
- backend/src/test/java/com/celuveat/restaurant/command/application/RestaurantReviewLikeServiceTest.java
- backend/src/test/java/com/celuveat/restaurant/command/application/RestaurantReviewServiceTest.java
- backend/src/test/java/com/celuveat/restaurant/fixture/RestaurantReviewFixture.java
- backend/src/test/java/com/celuveat/restaurant/fixture/RestaurantReviewImageFixture.java
- backend/src/test/java/com/celuveat/restaurant/query/RestaurantReviewQueryServiceTest.java
```
리뷰 조회시 이미지, 평점, 좋아요 여부를 포함하여 응답합니다
```
`reataurant_review` -> `like_count` 컬럼 추가
```sql
ALTER TABLE restaurant_review ADD COLUMN (like_count INT);
UPDATE restaurant_review SET restaurant_review.like_count = 0 WHERE restaurant_review.like_count IS NULL;
```
---
- #550 위에서 작업하였습니다.
<br>
[리뷰 범위 입니다!](https://github.com/woowacourse-teams/2023-celuveat/pull/553/files/4c38650c29a697411539e361918ad04a02ae0370..6c2e39c694c676a0253af8433fa384c87c172265)
- close #552
> refactor: 리뷰 조회시 이미지, 평점, 좋아요 여부 포함하여 응답

- backend/src/main/java/com/celuveat/admin/command/application/AdminService.java
- backend/src/main/java/com/celuveat/celeb/exception/CelebExceptionType.java
- backend/src/test/java/com/celuveat/admin/command/application/AdminServiceTest.java
1. 사진없이 데이터 저장할 때 음식점 이미지 데이터가 공백으로 저장되는 현상을 아예 저장되지 않도록 수정했습니다.
<br>
- close #633 
<br>
> fix: 사진없이 데이터 저장시 음식점 이미지가 공백으로 저장되는 버그 수정

- frontend/src/components/CelebProfile/CelebProfile.tsx
- frontend/src/components/CelebProfile/index.tsx
- frontend/src/components/MiniRestaurantCard/MiniRestaurantCard.tsx
- frontend/src/hooks/useOnClickBlock.ts
- frontend/src/pages/MainPage/BannerSection/components/BannerSlider.tsx
- frontend/src/pages/MainPage/CelebBestSection/CelebBestSection.tsx
`useOnClickBlock` 이라는 커스텀 훅을 생성하여 오류를 개선하였습니다.
```typescript
interface UseOnClickBlockProps {
callback: () => void;
}
const useOnClickBlock = ({ callback }: UseOnClickBlockProps) => {
const [isDragging, setIsDragging] = useState<boolean>(false);
const handleMouseDown = useCallback(() => {
setIsDragging(false);
}, []);
const handleMouseMove = useCallback(() => {
setIsDragging(true);
}, []);
const handleClick = () => {
if (isDragging) return;
callback();
};
return { onMouseDown: handleMouseDown, onMouseMove: handleMouseMove, onClick: handleClick };
};
```
`isDragging` : 드래그중인지 여부를 불리언 값의 상태로 관리합니다.
`handleMouseDown` : 마우스를 누르면 우선 `isDragging`을`false`로 초기화합니다.
`handleMouseMove` : 이후 마우스를 누른 상태로 움직인다면`isDragging`을`true`로 상태를 업데이트합니다.
`handleClick` : 마우스를 올렸을 때 (손에서 때었을 때) 드래그 중이라면 early …
> hotfix: 드래그 이벤트와 클릭 이벤트 분리

- frontend/src/components/MiniRestaurantCard/MiniRestaurantCard.tsx
```
useNavigate에서 window.location.href로 대치함으로써 문제를 해결하였습니다.
물론 이렇게 된다면 새로고침이 발생하면서 리액트쿼리의 캐싱기능이 무효화됩니다.
하지만 캐싱에 앞서 정상적으로 동작하는 것이 우선이기에 
추후 더 나은 해결방안이 나온다면 개선해보겠습니다.
```
<br><br>
https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/fff8fc84-3238-4c03-8b34-157be9f8e307
- close #688
<br><br>
> hotfix: 상세페이지에서 주변다른식당으로 이동시 뒤로가기 기능이 동작하지 않는 오류 개선

- frontend/src/pages/RestaurantDetailPage/Skeleton.tsx
```
스켈레톤 디자인 속성 수정을 통해 오버플로우 현상을 개선하였습니다.
```
https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/aed73b83-0fe1-4dd8-bae3-fbe5f5b9042e
<br><br>
- close #690 
<br><br>
> design: 스켈레톤 디자인 속성 수정

- frontend/cypress/e2e/desktop/like.cy.ts
- frontend/cypress/e2e/desktop/login.cy.ts
- frontend/cypress/e2e/mobile/login.cy.ts
- frontend/cypress/support/commands.ts
- frontend/src/components/@common/InfoButton/InfoButton.tsx
- frontend/src/components/BottomNavBar/BottomNavBar.tsx
- frontend/src/components/InfoDropDown/InfoDropDown.tsx
- frontend/src/components/RestaurantDetailLikeButton/RestaurantDetailLikeButton.tsx
- frontend/src/hooks/context/ReviewModalProvider.tsx
- frontend/src/hooks/server/useCheckLogin.ts
- frontend/src/pages/WishListPage.tsx
```
cypress 에러 수정 및 e2e 테스트 코드 추가작성하였습니다.
```
https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/9eecedec-cc4f-40c0-9fe6-df462624e6c6
- 모바일
https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/1506abb9-2310-4e73-8b20-0aa54e55eb53
- 데스크탑
https://github.com/woowacourse-teams/2023-celuveat/assets/102432453/fb0876b8-2e89-4d33-bf15-79eaaae860c3
추가적으로 `getProfile` 요청의 경우 훅이 있음에도 재사용되지 않아 공통된 로직에 훅을 적용하였습니다.
<br><br>
- close #700 
<br><br>
> refactor: E2E 테스트 코드 개선 및 추가 작성

- frontend/src/components/@common/VideoCarousel/VideoCarousel.tsx
- frontend/src/components/MiniRestaurantCard/MiniRestaurantCard.tsx
- frontend/src/components/YoutubeEmbed/YoutubeEmbed.tsx
- frontend/src/components/YoutubeEmbed/index.tsx
- frontend/src/pages/RestaurantDetailPage/DetailInformation.tsx
- frontend/src/pages/RestaurantDetailPage/RestaurantVideoList.tsx
주변다른식당 클릭 이후 뒤로가기가 동작하지 않는 오류를 window.location.href 를 사용하지 않고 기존 방식과 동일하게 `useNavigation`을 사용하여 개선하였습니다.
에러의 발생원인은 `iframe` 태크에 있었습니다.
iframe을 재사용하면서 다른 콘텐츠를 가리키도록 src 속성만 변경하면 콘텐츠 탐색으로 간주되어 iframe의 현재 src가 브라우저의 window.history 스택에 푸시되기 때문에 뒤로가기가 정상적으로 동작하지 않던 것이었습니다.
그래서 key props를 Iframe에 삽입해주어 iframe을 파괴하고 소스 코드를 변경해야 할 때마다 다시 생성함으로써 해결하였습니다.
관련 자료 : https://www.aleksandrhovhannisyan.com/blog/react-iframes-back-navigation-bug/
<br><br>
- close #688 
<br><br>
> hofix: 주변다른식당 클릭 이후 뒤로가기가 동작하지 않는 오류 개선
